### PR TITLE
Rel 20240919

### PR DESCRIPTION
**Pull request by adultplexdev**
20240919 - Update to fix issues with ADE changing their website structure (thx to adtdev20)

### CODE REVIEW

**Comment by ALittleCremeFraiche** [comment]
Recently broken by SSL error. From com.plexapp.agents.adultdvdempire.log you can see the issue: URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)> 
I have not yet been able to find a fix

**Comment by Dupplehouse** [comment]
Extremely new to this, but I have been able to get it "working" . I basically copied the shared libraries from the Phoenix package so that I could use the requests objects. 
```
import requests
from lxml.html import fromstring
```

Ran into a little problem where it was always going to an age confirmation page. Adding the cookie took care of this. 

```
    session = requests.session()
    cookies = {"ageConfirmed":"true"}
    session.cookies.update(cookies)
    response = session.get(ADE_SEARCH_MOVIES % query)
    html = response.text
    tree = fromstring(html)
```

This replaced the HTML.ElementFromUrl call:
```
    #for movie in HTML.ElementFromURL(ADE_SEARCH_MOVIES % query).xpath('//div[contains(@class,"row list-view-item")]'):
    for movie in tree.xpath('//div[contains(@class,"row list-view-item")]'):
```

I also changed the Update function:
```
    #html = HTML.ElementFromURL(ADE_MOVIE_INFO % metadata.id)
    session = requests.session()
    cookies = {"ageConfirmed":"true"}
    session.cookies.update(cookies)    
    response = session.get(ADE_MOVIE_INFO % metadata.id)
    html = fromstring(response.text)
```

And finally I noticed that the search results weren't bringing everything I expected back. I replaced the following where it is determining video format:

```
          #movie2 = movie.xpath('.//a[@title="DVD" or @title="dvd"]')
	  movie2 = movie.xpath('//div[@class="list-view-item-controls_content-type m-b-1"][contains(string(), "DVD-Video")]')
          if DEBUG: Log('Current title is DVD')
          if len(movie2) > 0:
            mediaformat = "dvd"

          # 2024-09-19 ADE dont use Blu-ray as its own category for the moment.
          #movie2 = movie.xpath('.//small[contains(text(),"Blu-ray")]')
          #if len(movie2) > 0:
          #  mediaformat = "br"

          #movie2 = movie.xpath('.//a[@title="VOD" or @title="vod"]')
          movie2 = movie.xpath('//div[@class="list-view-item-controls_content-type m-b-1"][contains(string(), "Video On Demand")]')
	  if DEBUG: Log('Current title is VOD')
          if len(movie2) > 0:
            mediaformat = "vod"
```

Hope this helps.

-Dupplehouse

**Comment by ALittleCremeFraiche** [comment]
I also ended up getting it working in a very similar way, and have made it available: ALittleCremeFraiche/AdultDVDEmpire.bundle

**Comment by AyeUneek** [comment]
I've been trying to get the later builds to work.. the 20240919 agent shows up in Plex but when I attempt to search for results and I don't pull anything. I have tried the later builds in Plex but they fail to show up as an agent. I'm using a Mac OS version of PMS as well as a Sinology version of PMS. Can someone help me out to get the later builds to work or just any version where I can search for titles and it can actually pull results. Thanks for the help everyone!!!

**Comment by AyeUneek** [comment]
> I also ended up getting it working in a very similar way, and have made it available: ALittleCremeFraiche/AdultDVDEmpire.bundle

I tried using yours on a Mac PMS and sinology PMS server but they don't show up in the agents.. but if I go bak to the 202040919 build, it shows up but doesn't work.  Any help.. and yes its placed in the correct folder and as a .bundle

**Comment by Leffe64** [comment]
Have you tried the way I did it:

Use the 20240919 agent, edit the file " __init__.py", add the line "HTTP.SetHeader('Cookie', 'ageConfirmed=true')" just below the other "HTTP.SetHeader-line" (there is just one, on row 43)

**Comment by ALittleCremeFraiche** [comment]
> o

Sorry I'm not sure why that would be. You may need to check the log at Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.agents.adultdvdempire.log to see why it failed to load in. Let me know If the log throws up anything I can look into

**Comment by adultplexdev** [comment]
Update have been committed and should be working. See latest build.

**Comment by Leffe64** [comment]
There are two more things that needs to be fixed:

1. Add a default mediaformat since the section "title" might be missing and if so that movie wont be included in the result. Just below `if preference['ADEsearchtype'] == 'all':`  add `mediaformat = "dvd" ` 
2. Comment out the superseded code regarding the Releasedate. If the section "released" is missing that movie wont be included in the result.

**Pull request merged**
